{
 "title": "filemanager_request_monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "POST on /image",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/image\", method=\"POST\"}"
    }
   ]
  },
  {
   "title": "GET on /image/id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/image/{id:.+}\"}"
    }
   ]
  },
  {
   "title": "Get on /image/all",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/image/all\"}"
    }
   ]
  },
  {
   "title": "GET on /image/duplicates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/image/duplicates\"}"
    }
   ]
  }
 ]
}